@hostname = http://localhost:3000
@namespace = dummy.dev
@key = posts-dummy

### Retrive counter value
GET {{hostname}}/api/count?namespace={{namespace}}&key={{key}}


### Up counter value
POST {{hostname}}/api/count/up?namespace={{namespace}}&key={{key}}

